# Generated by Django 5.2.1 on 2025-06-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_labels_options_alter_labels_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
    ]
